// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDww6ayaVBeuYezlX3kpDM19AKo5YCNDxg',
    appId: '1:424818644802:web:4cd76a5975ca6f87f7dadb',
    messagingSenderId: '424818644802',
    projectId: 'mynotes-60920',
    authDomain: 'mynotes-60920.firebaseapp.com',
    storageBucket: 'mynotes-60920.appspot.com',
    measurementId: 'G-G7LPS5S31J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYn8moviYiabtMqeewUYlE-5E2KzfI1OY',
    appId: '1:424818644802:android:535d6ad65561ffeaf7dadb',
    messagingSenderId: '424818644802',
    projectId: 'mynotes-60920',
    storageBucket: 'mynotes-60920.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkrwvw5sNQs7fqxpbG6Pyqwg56cjWkEbg',
    appId: '1:424818644802:ios:0c90a7135cc7f821f7dadb',
    messagingSenderId: '424818644802',
    projectId: 'mynotes-60920',
    storageBucket: 'mynotes-60920.appspot.com',
    iosClientId: '424818644802-kup5e06alhcngpc3khenvudm6p4utsro.apps.googleusercontent.com',
    iosBundleId: 'com.testing.mynotes',
  );
}
